new ancestor
Fidel9/SauceDemo pull request #1
Opened 2021-11-24 22:51 UTC by Fidel9

сегодня допишу остальные локаторы

2021-11-25 11:27 UTC, mikola-2 approved these changes

2021-11-25 18:41 UTC, mikola-2 approved these changes

2021-11-27 16:23 UTC, Fidel9 commented
не много поспешил и в методе в  параметры поставил обьект String zipOrPostal который принимает строку, а должен принимать  int цифры. Если он принимает только цифры то там баг так как тест может проходить так же толь ко с буквами. Но я не нашел ни какой инфы какой должен быть zip/postal код. Могут ли проходить только цифры или только буквы, или все вместе. Не хватает README.md

2021-11-27 16:39 UTC, Fidel9 commented
в задании еще не хватает сообщений

2021-11-28 10:45 UTC, mikola-2 requested changes

2021-11-28 10:45 UTC, mikola-2 commented on src/test/java/pages/CheckoutYourInformation.java
> +public class CheckoutYourInformation extends BasePage {
Чтобы не было путаницы, лучше добавлять в конце названия класса или Page или Test. В данном случае, CheckoutYourInformationPage.

2021-11-28 10:45 UTC, mikola-2 commented on src/test/java/pages/BasePage.java
> +import io.github.bonigarcia.wdm.WebDriverManager;
Ctrl + Alt + L - убирает и лишние импорты. Но это уже просто придирка. Так как больше не к чему зацепиться) Отличная работа!

2021-11-28 10:45 UTC, mikola-2 commented on src/test/java/pages/CheckoutYourInformation.java
> +    public void criticalPathTest() {
На всякий случай повторю.
В тестовых классах имена заканчиваются на ...Test. Классы описывающие страницу, заканчиваются на ...Page. Имена тестовых методов, которые предваряются аннотацией @Test должны находиться только в классах Test, и их имена должны звучать максимально понятно.
NextPageUnderCheckoutYourInformationPage() звучит норм, но должно быть с маленькой буквы. А вот метод criticalPathTest() я бы переименовал, убрав слово Test. В этом методе нет ассертов и он ничего не проверяет, а значит и тестом зваться не может.

2021-11-28 10:45 UTC, mikola-2 commented on src/test/java/tests/NewTest.java
> +public class NewTest extends BaseTest {
Отлично, что потренировался. Теперь можно убрать отсюда аннотации для тест раннера, чтобы он не считал этот класс тестовым.

2021-11-28 10:45 UTC, mikola-2 commented on src/test/java/pages/InventoryPage.java
> +        public static final String ADD_PRODUCT_BUTTON = "//div[div[div[div[a[div[@class='inventory_item_name'[text()='%s']]]]]//button";
В этом xPath лишняя div[ в начале, как я понимаю. И не хватает закрывающей квадратной скобки поле @class='inventory_item_name'
Тест у меня не проходил.

2021-11-28 10:45 UTC, mikola-2 commented on src/test/java/tests/LoginPagesTest.java
>      public void criticalPathTest() {
В твоём проекте два одинаково именующихся метода в разных классах. Делают ли они одно и то же?

2021-11-28 10:45 UTC, mikola-2 commented on src/test/java/tests/LoginPagesTest.java
> +        Assert.assertEquals(loginPage.getErrorMessage(),"");
Тут в ассерте не хватает ожидаемого значения и сообщения, если тест упадёт.

2021-11-28 10:45 UTC, mikola-2 commented on src/test/java/tests/LoginPagesTest.java
> +        loginPage.login("","secret_sauce");
Тут в тесте ты не вводишь юзернейм в поле и в ассерте не хватает ожидаемого значения и сообщения, если тест упадёт.

2021-11-28 10:45 UTC, mikola-2 commented on src/test/java/pages/LoginPage.java
> +    public static final By ERROR_MESSAGE = By.cssSelector(".error_message_container");
.error_message_container тут на сайте дефис, а не нижнее подчёркивание. Из-за этого негативные тесты на логин невалидные все.

2021-11-28 10:45 UTC, mikola-2 commented on src/test/java/pages/CheckoutYourInformation.java
> +        String thingsFromCatalog = driver.findElement(By.xpath("//div[@class='inventory_item_name']")).getText();
Тут две строковые переменные, которые ты нигде не используешь.

2021-11-28 10:45 UTC, mikola-2 commented on src/test/java/tests/CheckoutYourInformationTest.java
> +        Assert.assertEquals(overviewPage2,overviewPage1,"проверка правильности перехода на эту страницу");
Тут ты сравниваешь два значения, которые берёшь из одного и того же элемента.
Ассерт же нужен, чтобы сравнить актуальное и ожидаемое. Если нужно было проверить существование элемента на странице, то можно было сделать:
String textFromTitle= driver.findElement(By.xpath("//span[@class='title']")).getText();
Assert.assertEquals(textFromTitle, "CHECKOUT: YOUR INFORMATION", "Текст не соответствует ожидаемому.");

2021-11-28 10:45 UTC, mikola-2 commented on src/test/java/tests/CheckoutYourInformationTest.java
> +        Assert.assertEquals(checkoutYourInformation.getErrorMessage(),"Error: Postal Code is required",
Не понимаю, что ты проверяешь. На момент проверки я не вижу никакого сообщения об ошибке.

2021-11-28 15:59 UTC, Fidel9 commented on src/test/java/tests/CheckoutYourInformationTest.java
> +        Assert.assertEquals(checkoutYourInformation.getErrorMessage(),"Error: Postal Code is required",
Я еще  перепутал названия метода; но уже поменял . Я проверяю zip/postal код на ввод только букв и ожидаю ошибку, так как думаю что код должен состоять только из цифр. Но если так было задумано что можно вводить и цифры, и буквы то да, нужно поменять асерт или сам тест поменять на другую проверку.

2021-11-28 17:05 UTC, mikola-2 approved these changes

2021-11-28 17:44 UTC, merged